### PR TITLE
Couple of bugfixes

### PR DESCRIPTION
**Pull request by Vadman97**
Just ran into a couple of things and thought I would push quick fixes. Check the commit messages. Really cool though and super helpful extension!

### CODE REVIEW

**Comment by jonluca** [comment]
this is amazing. thanks!!! apologies in advance for having to deal with this codebase.

**Comment by Vadman97** [comment]
Oh I actually found it super easy to find stuff and edit! I was just wondering how the data.json is generated, is there some preprocessing code that's not part of the repo?

**Comment by jonluca** [comment]
Yup, I have a private repo with a full RMP scraper. It was public, but I got a cease&desist from them for it :/

I can add you to it though if you want

**Comment by Vadman97** [comment]
Huh yeah I was wondering too why you chose to preprocess but I guess any use of their data (since they don't have a public API) is against their TOS... and preprocessing hides the data better than having requests from the extension all the time from each user.
Sure though, that would be good though probably most of the features to be added are on this side of the app.

**Pull request merged**
